### ISSUE TITLE
Use stable links

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/nsis-feedstock#23]
Currently the links seem to be changing here. We need to pick something that is static

https://github.com/conda-forge/nsis-feedstock/pull/20#discussion_r1085400238

https://github.com/conda-forge/nsis-feedstock/pull/20#discussion_r1085400395

cc @isuruf

**Comment by jaimergp** [comment]
Hm, I had not seen those comments, sorry! I'll address them next week.

**Comment by jakirkham** [comment]
No worries. Thanks for following up 🙏

**Comment by jakirkham** [comment]
We could just upload those on a (date-based?) tag on this repo

**Comment by jakirkham** [comment]
@jezdez , appears Anaconda has the same issue with this recipe. Maybe we can coordinate on the solution here?

**Comment by jaimergp** [comment]
Given how important NSIS is for the installers, maybe something like `conda/nsis-mirror` which the community can control (instead of personal repos), would be super welcome?

**Comment by jakirkham** [comment]
In the past we've just attached this sort of thing to the feedstock directly. We can always add maintainers. It's a pretty lightweight solution

That said, don't have strong feelings. @isuruf , what do you think?

**Comment by jezdez** [comment]
> @jezdez , appears Anaconda has the same issue with this recipe. Maybe we can coordinate on the solution here?

Yeah, that's a good idea, I've filed an internal ticket about this so that @skupr-anaconda and others can take a look.

**Comment by jezdez** [comment]
For the record, the recipe for nsis lives (IIUC) here: https://github.com/AnacondaRecipes/aggregate/blob/master/nsis-feedstock/recipe/meta.yaml

**Comment by dbast** [comment]
why not use a repo in one of the Github orgs (conda-forge/conda/conda-incubator/AnacondaRecipes), uploads and changes can then be done via PRs... I am not aware of an internal Anaconda WebService that allows binary uploads via PR so that uploads and its operation are transparent to everybody.

**Comment by jaimergp** [comment]
We basically need something like https://github.com/kichik/nsis but with synced Releases (not just tags) that bundle the binary artifacts, and all the plugins.

**Comment by jaimergp** [comment]
[I added some logic in a fork of that repo](https://github.com/jaimergp/nsis-mirror/releases). We can transfer it to `conda-incubator` or similar once we are happy with it.

**Comment by jaimergp** [comment]
The mirror is now ready, and a PR is ready for review: https://github.com/conda-forge/nsis-feedstock/pull/24

Thanks!
