### ISSUE TITLE
Reason for not using the latest NSIS release ?

### ISSUE THREAD

**Issue by ThomasLecocq** [conda-forge/nsis-feedstock#6]
Hi,

We're having small issues with building installers on windows (inlcuding problems with too-long-names (like 100 char, you know, super long... ) and I was now wondering why the installed NSIS via conda is 2.46 (Released on December 6th, 2009) and not 3.0.1 (Released on December 11th, 2016) ?

Cheers,
Tom

**Comment by ThomasLecocq** [comment]
forget about it, conda/free has 3.0.1 in the default channel.

**Comment by jakirkham** [comment]
We were trying to match what `defaults` had, which was this old release. Since that has changed we can certainly update it. Have added PR ( https://github.com/conda-forge/nsis-feedstock/pull/7 ) to do so. Though, as this is a community, feel free to add PRs yourself to update things as needed.

**Comment by jakirkham** [comment]
Turns out a lot of extensions got bundled with the `defaults` copy of `nsis`. So bumping the version was not enough. We have just now fixed this in PR ( https://github.com/conda-forge/nsis-feedstock/pull/9 ).

**Comment by ThomasLecocq** [comment]
@megies this should be ok for us to build win ObsPy installs
